import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import * as React from "react";
import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning={true}>
      <body className={cn("bg-background font-sans", fontSans.variable)}>
        <ThemeProvider attribute={"class"} defaultTheme={"system"}>
          <Toaster />
          <Header />
          <main className="mx-auto mt-[72px] w-full max-w-[85rem] px-4 py-5">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
